# Generated by Django 4.0.1 on 2022-03-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('basePrice', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('finalPrice', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('stock', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pic1', models.ImageField(blank=True, default=None, null=True, upload_to='media/images/')),
                ('pic2', models.ImageField(blank=True, default=None, null=True, upload_to='media/images/')),
                ('pic3', models.ImageField(blank=True, default=None, null=True, upload_to='media/images/')),
                ('pic4', models.ImageField(blank=True, default=None, null=True, upload_to='media/images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maincategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcategory')),
            ],
        ),
    ]
