# Generated by Django 4.0.1 on 2022-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_buyer_seller_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/images'),
        ),
    ]
