# Generated by Django 4.0.1 on 2022-04-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_newslatter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField(blank=True, default=0, null=True)),
                ('mode', models.CharField(blank=True, default='COD', max_length=20, null=True)),
                ('paymentstatus', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('orderstatus', models.CharField(blank=True, default='Net Packed', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rppid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpoid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpsid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
                ('products', models.ManyToManyField(to='mainApp.Product')),
            ],
        ),
    ]
