# Generated by Django 4.0.1 on 2022-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_remove_checkout_products_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutproducts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
