# Generated by Django 4.0.1 on 2022-04-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_checkoutproducts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='date',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
