# Generated by Django 4.0.1 on 2022-04-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_remove_checkoutproducts_date_alter_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
