# Generated by Django 4.0.1 on 2022-04-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_checkout1_checkoutproducts1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping', models.IntegerField(blank=True, default=0, null=True)),
                ('final', models.IntegerField(blank=True, default=0, null=True)),
                ('mode', models.CharField(blank=True, default='COD', max_length=20, null=True)),
                ('paymentstatus', models.CharField(blank=True, default='Pending', max_length=20, null=True)),
                ('orderstatus', models.CharField(blank=True, default='Net Packed', max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('rppid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpoid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('rpsid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('q', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.checkout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkoutproducts1',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='checkoutproducts1',
            name='product',
        ),
        migrations.DeleteModel(
            name='Checkout1',
        ),
        migrations.DeleteModel(
            name='CheckoutProducts1',
        ),
    ]
