# Generated by Django 4.0.1 on 2022-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_checkout_checkoutproducts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='orderstatus',
            field=models.CharField(blank=True, default='Not Packed', max_length=20, null=True),
        ),
    ]
