# Generated by Django 4.0.1 on 2022-04-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_alter_checkout_orderstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutproducts',
            name='product',
        ),
        migrations.AddField(
            model_name='checkoutproducts',
            name='productid',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
