# Generated by Django 4.0.1 on 2022-05-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0018_contact_alter_newslatter_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Newslatter',
        ),
    ]
